// Graph Export Tests — PNG generation, watermarks, dimensions.

import { describe, it, expect } from 'vitest';
import { GraphExporter } from '../../../packages/core/knowledge/graph-export.js';
import type { GraphStats } from '../../../packages/core/knowledge/graph-visualization.js';

function makeSvgContent(): string {
  return `
    <circle cx="100" cy="100" r="10" fill="#4A7FBA"/>
    <circle cx="200" cy="200" r="15" fill="#E8A838"/>
    <line x1="100" y1="100" x2="200" y2="200" stroke="#E2E4E9" stroke-width="1"/>
  `;
}

function makeStats(): GraphStats {
  return {
    totalNodes: 42,
    totalEdges: 87,
    nodesByType: { person: 20, topic: 12, document: 10 },
    averageConnections: 4.14,
    mostConnectedNode: { id: 'hub', label: 'Alice Hub', connections: 15 },
    graphDensity: 0.1,
    growthRate: 5,
  };
}

describe('GraphExporter', () => {
  const exporter = new GraphExporter();

  it('generates PNG bytes from SVG input', () => {
    const result = exporter.exportAsPng(makeSvgContent());

    expect(result.pngBytes).toBeInstanceOf(Uint8Array);
    expect(result.pngBytes.length).toBeGreaterThan(0);

    // Verify PNG signature
    expect(result.pngBytes[0]).toBe(137);
    expect(result.pngBytes[1]).toBe(80);  // P
    expect(result.pngBytes[2]).toBe(78);  // N
    expect(result.pngBytes[3]).toBe(71);  // G

    // Verify dimensions match defaults
    expect(result.width).toBe(1920);
    expect(result.height).toBe(1080);

    // Verify timestamp is present
    expect(result.timestamp).toBeTruthy();
    expect(result.timestamp.length).toBeGreaterThan(0);
  });

  it('export includes timestamp watermark when includeTimestamp=true', () => {
    const result = exporter.exportAsPng(makeSvgContent(), { includeTimestamp: true });

    // Decode the SVG portion of the output to check for watermark
    const decoder = new TextDecoder();
    const text = decoder.decode(result.pngBytes);
    expect(text).toContain('Generated by Semblance');
  });

  it('export respects custom width/height dimensions', () => {
    const result = exporter.exportAsPng(makeSvgContent(), {
      width: 800,
      height: 600,
    });

    expect(result.width).toBe(800);
    expect(result.height).toBe(600);

    // Verify width is encoded in IHDR (bytes 16-19 after PNG signature = bytes 8-11 of IHDR data)
    // PNG signature is 8 bytes, IHDR starts at offset 8
    // IHDR: 4 bytes length + 4 bytes type + width at offset 0 of data
    const widthOffset = 8 + 4 + 4; // signature + length + type
    const encodedWidth = (result.pngBytes[widthOffset]! << 24) |
                         (result.pngBytes[widthOffset + 1]! << 16) |
                         (result.pngBytes[widthOffset + 2]! << 8) |
                         result.pngBytes[widthOffset + 3]!;
    expect(encodedWidth).toBe(800);

    const heightOffset = widthOffset + 4;
    const encodedHeight = (result.pngBytes[heightOffset]! << 24) |
                          (result.pngBytes[heightOffset + 1]! << 16) |
                          (result.pngBytes[heightOffset + 2]! << 8) |
                          result.pngBytes[heightOffset + 3]!;
    expect(encodedHeight).toBe(600);
  });

  it('export without stats omits statistics overlay', () => {
    const resultWithStats = exporter.exportAsPng(makeSvgContent(), {
      includeStats: true,
      stats: makeStats(),
    });

    const resultWithoutStats = exporter.exportAsPng(makeSvgContent(), {
      includeStats: false,
    });

    const decoderWith = new TextDecoder();
    const textWith = decoderWith.decode(resultWithStats.pngBytes);
    const textWithout = decoderWith.decode(resultWithoutStats.pngBytes);

    // With stats includes node/edge counts
    expect(textWith).toContain('Nodes: 42');
    expect(textWith).toContain('Edges: 87');
    expect(textWith).toContain('Alice Hub');

    // Without stats does not contain stats overlay
    expect(textWithout).not.toContain('Nodes: 42');
    expect(textWithout).not.toContain('Edges: 87');
  });
});
