/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{ts,tsx}',
    './index.html',
    '../semblance-ui/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        semblance: {
          'bg-dark': '#1A1D2E',
          'bg-light': '#FAFBFC',
          primary: '#4A7FBA',
          accent: '#E8A838',
          success: '#3DB87A',
          attention: '#E85D5D',
          muted: '#8B93A7',
          'primary-hover': '#3D6CA3',
          'primary-active': '#325A8A',
          'primary-subtle': '#EBF2F9',
          'primary-subtle-dark': '#1E2A3E',
          'accent-hover': '#D4952F',
          'accent-subtle': '#FFF6E8',
          'success-subtle': '#EDFAF2',
          'attention-subtle': '#FEF0F0',
          'surface-1': '#FFFFFF',
          'surface-1-dark': '#222538',
          'surface-2': '#F5F6F8',
          'surface-2-dark': '#2A2D42',
          border: '#E2E4E9',
          'border-dark': '#363952',
          'text-primary': '#1A1D2E',
          'text-primary-dark': '#ECEDF0',
          'text-secondary': '#5A6070',
          'text-secondary-dark': '#9BA0B0',
          'text-tertiary': '#8B93A7',
        },
      },
      fontFamily: {
        ui: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'Consolas', 'monospace'],
        display: ['DM Serif Display', 'Fraunces', 'Georgia', 'serif'],
      },
      fontSize: {
        xs: ['0.6875rem', { lineHeight: '1.45' }],
        sm: ['0.8125rem', { lineHeight: '1.45' }],
        base: ['1rem', { lineHeight: '1.5' }],
        md: ['1.125rem', { lineHeight: '1.4' }],
        lg: ['1.25rem', { lineHeight: '1.35' }],
        xl: ['1.5rem', { lineHeight: '1.3' }],
        '2xl': ['1.875rem', { lineHeight: '1.25' }],
        '3xl': ['2.375rem', { lineHeight: '1.2' }],
        display: ['3rem', { lineHeight: '1.1' }],
      },
      spacing: {
        0: '0px',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
        20: '80px',
      },
      borderRadius: {
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(0,0,0,0.05)',
        md: '0 2px 8px rgba(0,0,0,0.08)',
        lg: '0 4px 16px rgba(0,0,0,0.12)',
        xl: '0 8px 32px rgba(0,0,0,0.16)',
        focus: '0 0 0 3px rgba(74,127,186,0.3)',
        'sm-dark': '0 1px 2px rgba(0,0,0,0.3)',
        'md-dark': '0 2px 8px rgba(0,0,0,0.3)',
        'lg-dark': '0 4px 16px rgba(0,0,0,0.3)',
        'xl-dark': '0 8px 32px rgba(0,0,0,0.3)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '250ms',
        slow: '400ms',
        cinematic: '800ms',
      },
      transitionTimingFunction: {
        out: 'cubic-bezier(0.16, 1, 0.3, 1)',
        'in-out': 'cubic-bezier(0.65, 0, 0.35, 1)',
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      maxWidth: {
        'container-sm': '640px',
        'container-md': '768px',
        'container-lg': '1024px',
        'container-xl': '1200px',
      },
      keyframes: {
        'loading-pulse': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '1' },
        },
        'toast-enter': {
          '0%': { transform: 'translateY(16px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'toast-exit': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'status-pulse': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
      },
      animation: {
        'loading-pulse': 'loading-pulse 1.5s ease-in-out infinite',
        'toast-enter': 'toast-enter 250ms cubic-bezier(0.16, 1, 0.3, 1)',
        'toast-exit': 'toast-exit 150ms cubic-bezier(0.16, 1, 0.3, 1)',
        'status-pulse': 'status-pulse 1.5s ease-in-out infinite',
        'fade-in': 'fade-in 800ms cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
};
