/**
 * License Key Utilities — Shared signing logic for test key generation.
 *
 * Used by generate-test-key.ts and test suites.
 * The private key is NEVER embedded — it must be provided as a parameter.
 */

import { createPrivateKey, createPublicKey, sign, generateKeyPairSync } from 'node:crypto';

// ─── Types ──────────────────────────────────────────────────────────────

export type LicenseTier = 'founding' | 'digital-representative' | 'lifetime';

export interface LicenseKeyPayload {
  tier: LicenseTier;
  sub: string;
  iat: number;
  exp?: number;
  seat?: number;
}

export interface GeneratedLicenseKey {
  key: string;
  payload: LicenseKeyPayload;
  header: { alg: string; typ: string };
}

export interface Ed25519KeyPair {
  publicKeyPem: string;
  privateKeyPem: string;
}

// ─── Helpers ────────────────────────────────────────────────────────────

export function base64urlEncode(data: Buffer | string): string {
  const buf = typeof data === 'string' ? Buffer.from(data) : data;
  return buf.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

export function base64urlDecode(str: string): Buffer {
  let base64 = str.replace(/-/g, '+').replace(/_/g, '/');
  const padding = base64.length % 4;
  if (padding === 2) base64 += '==';
  else if (padding === 3) base64 += '=';
  return Buffer.from(base64, 'base64');
}

// ─── Key Generation ─────────────────────────────────────────────────────

/**
 * Generate a fresh Ed25519 keypair for testing.
 * NEVER use this in production — production keys are generated by generate-license-keypair.ts.
 */
export function generateTestKeypair(): Ed25519KeyPair {
  const { publicKey, privateKey } = generateKeyPairSync('ed25519');
  return {
    publicKeyPem: publicKey.export({ type: 'spki', format: 'pem' }) as string,
    privateKeyPem: privateKey.export({ type: 'pkcs8', format: 'pem' }) as string,
  };
}

// ─── License Key Signing ────────────────────────────────────────────────

/**
 * Generate a signed sem_ license key using the provided private key PEM.
 *
 * @param privateKeyPem — Ed25519 private key in PEM format
 * @param options — tier, expiry, subject, seat number
 * @returns The signed license key string and its decoded components
 */
export function generateLicenseKey(
  privateKeyPem: string,
  options: {
    tier: LicenseTier;
    expiresInDays?: number;
    subject?: string;
    seat?: number;
  },
): GeneratedLicenseKey {
  const header = { alg: 'EdDSA', typ: 'LIC' };
  const headerB64 = base64urlEncode(JSON.stringify(header));

  const now = Math.floor(Date.now() / 1000);
  const payload: LicenseKeyPayload = {
    tier: options.tier,
    sub: options.subject ?? `test-${Date.now()}`,
    iat: now,
  };

  if (options.expiresInDays !== undefined && options.expiresInDays > 0) {
    payload.exp = now + (options.expiresInDays * 86400);
  }

  if (options.seat !== undefined) {
    payload.seat = options.seat;
  }

  const payloadB64 = base64urlEncode(JSON.stringify(payload));

  const privateKey = createPrivateKey(privateKeyPem);
  const signingInput = Buffer.from(`${headerB64}.${payloadB64}`);
  const signature = sign(null, signingInput, privateKey);
  const signatureB64 = base64urlEncode(signature);

  return {
    key: `sem_${headerB64}.${payloadB64}.${signatureB64}`,
    payload,
    header,
  };
}

/**
 * Extract the public key PEM from a private key PEM.
 */
export function derivePublicKey(privateKeyPem: string): string {
  const privateKey = createPrivateKey(privateKeyPem);
  const publicKey = createPublicKey(privateKey);
  return publicKey.export({ type: 'spki', format: 'pem' }) as string;
}

/**
 * Decode the payload from a sem_ license key (without verifying the signature).
 */
export function decodeLicensePayload(key: string): LicenseKeyPayload | null {
  if (!key.startsWith('sem_')) return null;
  const segments = key.slice(4).split('.');
  if (segments.length !== 3) return null;

  try {
    return JSON.parse(base64urlDecode(segments[1]!).toString('utf-8')) as LicenseKeyPayload;
  } catch {
    return null;
  }
}
