import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useTranslation } from 'react-i18next';
import { statusConfig, formatLastSynced } from './ConnectorCard.types';
import './ConnectorCard.css';
export function ConnectorCard({ id, displayName, description, status, isPremium, userEmail, lastSyncedAt, icon, onConnect, onDisconnect, onSync, }) {
    const { t } = useTranslation('connections');
    const { dotColor, textColor } = statusConfig[status];
    const isConnected = status === 'connected';
    const isPending = status === 'pending';
    const rootClass = `connector-card surface-slate${isConnected ? ' connector-card--connected' : ''}`;
    return (_jsxs("div", { className: rootClass, "data-testid": `connector-card-${id}`, children: [_jsxs("div", { className: "connector-card__top", children: [_jsxs("div", { className: "connector-card__info", children: [icon && (_jsx("div", { className: "connector-card__icon", children: icon })), _jsxs("div", { className: "connector-card__text", children: [_jsxs("div", { className: "connector-card__name-row", children: [_jsx("h3", { className: "connector-card__name", children: displayName }), isPremium && (_jsx("span", { className: "connector-card__dr-badge", children: t('card.dr_badge') }))] }), _jsx("p", { className: "connector-card__description", children: description })] })] }), _jsxs("div", { className: "connector-card__actions", children: [!isConnected && !isPending && (_jsx("button", { type: "button", className: "btn btn--opal btn--sm", onClick: () => onConnect(id), children: _jsx("span", { className: "btn__text", children: t('card.btn_connect') }) })), isConnected && (_jsxs(_Fragment, { children: [_jsx("button", { type: "button", className: "connector-card__btn connector-card__btn--sync", onClick: () => onSync(id), children: t('card.btn_sync') }), _jsx("button", { type: "button", className: "connector-card__btn connector-card__btn--disconnect", onClick: () => onDisconnect(id), children: t('card.btn_disconnect') })] })), isPending && (_jsx("span", { className: "connector-card__pending-text", children: t('card.pending_text') }))] })] }), _jsxs("div", { className: "connector-card__status", children: [_jsxs("div", { className: "connector-card__status-left", children: [_jsx("span", { className: `connector-card__status-dot connector-card__status-dot--${status}` }), _jsx("span", { className: `connector-card__status-text connector-card__status-text--${status}`, style: status !== 'disconnected' ? { color: textColor } : { fontSize: 'inherit', fontWeight: 'inherit', textTransform: 'none', letterSpacing: 'inherit' }, children: t(`status.${status}`) }), isConnected && userEmail && (_jsx("span", { className: "connector-card__status-email", children: userEmail }))] }), isConnected && lastSyncedAt && (_jsx("span", { className: "connector-card__status-sync", children: t('card.synced_prefix', { time: formatLastSynced(lastSyncedAt) }) }))] })] }));
}
//# sourceMappingURL=ConnectorCard.web.js.map